#!/bin/bash

echo "🌐 PTO Agent Domain Setup Script"
echo "================================="
echo ""

echo "📋 Domain Configuration Steps:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Select your 'pto-agent-main' project"
echo "3. Go to Settings → Domains"
echo "4. Add these domains:"
echo "   - ptoagent.app"
echo "   - www.ptoagent.app"
echo ""

echo "🔧 Environment Variables to Add:"
echo "In your Vercel project settings → Environment Variables:"
echo ""
echo "NEXT_PUBLIC_BASE_URL=https://ptoagent.app"
echo "NEXT_PUBLIC_APP_URL=https://ptoagent.app"
echo "NEXT_PUBLIC_DOMAIN=ptoagent.app"
echo ""

echo "🔐 Update External Services:"
echo ""
echo "Clerk Configuration:"
echo "1. Go to https://dashboard.clerk.com"
echo "2. Select your application"
echo "3. Go to Configure → Domains"
echo "4. Add: https://ptoagent.app"
echo "5. Update webhook URL to: https://ptoagent.app/api/webhooks/clerk"
echo ""

echo "Stripe Configuration (if using):"
echo "1. Go to https://dashboard.stripe.com"
echo "2. Go to Developers → Webhooks"
echo "3. Update endpoint to: https://ptoagent.app/api/webhooks/stripe"
echo ""

echo "✅ After completing these steps:"
echo "1. Your domain will be live at https://ptoagent.app"
echo "2. SSL certificate will be automatically provisioned"
echo "3. CDN and edge network will be activated"
echo ""

echo "🧪 Test your domain:"
echo "1. Visit https://ptoagent.app"
echo "2. Test search functionality"
echo "3. Test user authentication"
echo "4. Verify all features work correctly"
echo ""

echo "📞 If you need help:"
echo "- Check Vercel dashboard for deployment status"
echo "- Review environment variables"
echo "- Check browser console for errors"
echo ""

echo "Domain setup complete! 🎉"